name: Deploy static site to GitHub Pages

on:
    push:
        branches:
            - static
    workflow_dispatch:

permissions:
    contents: read
    pages: write
    id-token: write

concurrency:
    group: pages
    cancel-in-progress: true

jobs:
    build:
        name: Build static site
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./packages/frontend
        steps:
            - uses: actions/checkout@v4

            - uses: pnpm/action-setup@v4
              with:
                  version: 9

            - uses: actions/setup-node@v4
              with:
                  node-version: 22
                  cache: pnpm
                  cache-dependency-path: ./packages/frontend/pnpm-lock.yaml

            - name: Setup Pages
              uses: actions/configure-pages@v5
              with:
                  # static_site_generator: nuxt
                  # generator_config_file: ./packages/frontend/nuxt.config.ts
                  token: ${{ secrets.ACTIONS_DEPLOY_PAGES_ENABLEMENT }}
                  enablement: true

            - name: Restore cache
              uses: actions/cache@v4
              with:
                  path: |
                      ./packages/frontend/node_modules
                      ./packages/frontend/.nuxt
                      ./packages/frontend/dist
                  key: ${{ runner.os }}-nuxt-build-${{ hashFiles('dist') }}
                  restore-keys: |
                      ${{ runner.os }}-nuxt-build-

            - name: Install dependencies
              run: pnpm install --frozen-lockfile

            - name: Generate static site
              run: pnpm generate

            - name: Upload artifact
              uses: actions/upload-pages-artifact@v3
              with:
                  path: ./packages/frontend/dist

    deploy:
        name: Deploy to GitHub Pages
        needs: build
        runs-on: ubuntu-latest
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        steps:
            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v5

